jpackage `
--input .\..\target\lib `
--name Sistema Contable `
--main-jar SistemaContable-1.8.4.jar `
--main-class com.nutrehogar.sistemacontable.application.MainClass `
--type exe `
--icon .\icon\icon.ico `
--vendor "Universidad Tecnológica de Panamá - LIC. EN DESARROLLO DE SOFTWARE (2016-M)" `
--description "Sistema de Contabilidad para Nutre Hogar" `
--app-version 1.8.4 `
--verbose `
--win-shortcut `
--win-menu `
--win-dir-chooser `
--runtime-image "C:\Users\Calci\.jdks\corretto-21.0.6" `
--resource-dir .\resource